# Generated by Django 2.1.3 on 2018-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasztan', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
