# Generated by Django 2.1.3 on 2018-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasztan', '0003_auto_20181214_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imagepath', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
